# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Collider
email: maker@collider.org
description: > # ignore newlines 
  A place for people to explore ideas through experimentation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://collider.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
social-media-img: "/img/social-media-img.png"
github_username:  Collider-UMD
# Build settings
markdown: kramdown
headings:
    - name: Contact
      content: "To get in touch, shoot an email to <a href='mailto: maker@collider.org'>maker@collider.org</a>"
    - name: Rules
      include: "rules.html"
    - name: Getting there
      content: "For directions, check out <a href=''>this video</a>"
rules:
    - rule: "Collider is always open, to everyone"
    - rule: "Nothing leaves the space without permission"
    - rule: "Clean up after yourself"
    - rule: "Request resources for projects <a href=''>here</a>"
    - rule: "Build something cool"
