# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Collider
description_subtext: > # ignore newlines 
  Circuit Building, Painting, Plumbing, Programming, Woodworking... People
  working in Collider have made autonomous hovercraft, works of art, a smart
  showerhead, a DDR machine, a lighthouse... you name it
email: maker@collider.org
description: > # ignore newlines 
  A place for people to explore ideas through experimentation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://collider.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
social-media-img: "/img/social-media-img.png"
github_username:  Collider-UMD
# Build settings
markdown: kramdown
collider_closed: TRUE
closed_text: WILL RELAUNCH ON DECEMBER 3rd, DURING LOCAL HACK DAY! SIGN UP "<a href='http://ter.ps/localhackday'>HERE</a>"
headings:
    - name: Contact
      content: "To get in touch, shoot an email to <a href='mailto:maker@collider.org'>maker@collider.org</a>"
    - name: Rules
      include: "rules.html"
    - name: Getting there
      content: "For directions, check out <a href='https://www.youtube.com/watch?v=EO2zxN0GSYw'>this video</a>"
rules:
    - rule: "Collider is always open, to everyone"
    - rule: "Clean up after yourself"
    - rule: "Build something cool"
    - rule: "<div style='height:1px'></div>"
    - rule: "Request resources for projects <a href='http://goo.gl/forms/51V5yXhUsq'>here</a>"
    - rule: "Please get permission before taking things out of the space"
